apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: jenkins
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port
  type: NodePort      # You can change to LoadBalancer if on cloud
